steps:
  - name: Report test coverage to DeepSource
    uses: deepsourcelabs/test-coverage-action@master
    with:
      key: React
      coverage-file: coverage.xml
      dsn: ${{ secrets.DEEPSOURCE_DSN }}
